/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module gui.about;

private import dfl.all;

class About: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.picturebox.PictureBox pictureBox1;
	dfl.label.Label label1;
	dfl.label.Label label2;
	dfl.label.Label label3;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeAbout();
		
		this.pictureBox1.image = Application.resources.getIcon(101);
		this.icon = Application.resources.getIcon(101);
	}
	
	private void initializeAbout() {
		// Do not manually modify this function.
		//~Entice Designer 0.8.2.1 code begins here.
		//~DFL Form
		formBorderStyle = dfl.form.FormBorderStyle.FIXED_DIALOG;
		maximizeBox = false;
		startPosition = dfl.form.FormStartPosition.CENTER_PARENT;
		text = "Sobre";
		clientSize = dfl.drawing.Size(258, 109);
		//~DFL dfl.picturebox.PictureBox=pictureBox1
		pictureBox1 = new dfl.picturebox.PictureBox();
		pictureBox1.name = "pictureBox1";
		pictureBox1.bounds = Rect(24, 36, 32, 32);
		pictureBox1.parent = this;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "Emulador de GameBoy";
		label1.bounds = Rect(80, 24, 160, 16);
		label1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.text = "Por Carlos Ballesteros Velasco";
		label2.bounds = Rect(80, 48, 160, 16);
		label2.parent = this;
		//~DFL dfl.label.Label=label3
		label3 = new dfl.label.Label();
		label3.name = "label3";
		label3.text = "1ª Versión Mayo 2007";
		label3.bounds = Rect(80, 72, 160, 16);
		label3.parent = this;
		//~Entice Designer 0.8.2.1 code ends here.
	}	
}

