/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module gui.gdebug.main;

private import dfl.all;

private import gui.gdebug.registers;


class DebugForm: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeDebugForm();
		
		with (new DebugRegisters()) {
			mdiParent = this;
			show();
		}
		
		// Other DebugForm initialization code here.
	}
	
	
	private void initializeDebugForm()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.2.1 code begins here.
		//~DFL Form
		isMdiContainer = true;
		text = "Debug Form";
		clientSize = dfl.drawing.Size(432, 379);
		//~Entice Designer 0.8.2.1 code ends here.
	}
}
